### PR TITLE
Add and Document Different Ways of Installing ROS on Different Platforms

### PR DESCRIPTION
**Pull request by Carlosted**
This makes it so that developers are not restricted to `Ubuntu` to contribute to this project. It adds documentation for MacOS users and also experimental support for a containerized environment with `docker`.

### CODE REVIEW

**Comment by JosephSaliba01** [comment]
Thanks for the contribution. Do you have experience using RobotStack? What advantages would it bring us besides multi-platform support? ROS2 works on both Windows and Linux so how is it different?

**Comment by Carlosted** [comment]
RoboStack is simply _"a bundling of the Robot Operating System (ROS)"_. It allows installing ROS and most of its popular packages through `conda`. This allows other platforms such as MacOS to install ROS1. I have an installation of ROS through `RoboStack` and every dependency this project uses is available; I was able to launch the simulations.

I believe the main branch of this project still uses `ros-noetic`. I know ROS2 is more multi-platform, and I have seen that there is some effort for this project to migrate to ROS2. If you prefer I could also work on project migration instead of merging this PR, although I don't have a lot of experience with ROS.

**Comment by JosephSaliba01** [comment]
I understand. Although we see the benefit, migrating our code base and workflow to another robotics library at the moment is rather expensive and risky due to upcoming deadlines. This is also why we suspended the ROS2 migration process you mentioned.

 Also, I am curious as to why you picked up our code base, are you working on your own robotics project?

**Comment by Carlosted** [comment]
No, I do not currently work on a robotics project, but I wish I could.

I'm currently in CEGEP, and will be entering McGill next semester (hopefully). This project inspires me, and so I set out to start working on it.

If there is anything you would need a helping hand on let me know. I will be trying to work on some of the issues posted regardless.

**Comment by amotaouakkil123** [comment]
Thanks for your contribution, we appreciate it. We plan on migrating to ROS 2 so as my co-lead said it would not make a ton of sense to have the ROS wrapper integrated. ROS 2 has so many more tools, it's more multi-platform and all, but it takes a second to get on it since we have other objectives for the repo.
If you want to work with ROS 2 to get an early lead on that or give us feedback on what we could work on, we welcome your input.

**Comment by Carlosted** [comment]
Great, thank you for your quick feedback.

I will close the PR then.

**Pull request closed without merging**
