### PR TITLE
Added motor speeds conversions, fix sim topics.

### PR DESCRIPTION
**Pull request by amotaouakkil123**
Added motor speed conversions. Still need to check the values for the motor speeds to make sure calculations are done correctly. Modified control.yml to allow for gazebo diff controller.

### CODE REVIEW

**Review by amotaouakkil123 — COMMENTED** [review]
Added motor conversions and fixed joint_states.

**Review by amotaouakkil123 — COMMENTED** [review]
All good

**Comment by amotaouakkil123** [comment]
Added motor conversions and fixed joint states.

**Comment by amotaouakkil123** [comment]
My bad, added unnecessary comments to see how the vs extension for it worked.

**Review by acoulombe — APPROVED** [review]

**Pull request merged**
